iio: imu: st_lsm6dsx: pre-allocate read buffer at bootstrap
Allocate device read buffer at boostrap and do not put it on the stack
since it will be pretty huge (~200B) and its size will increase
adding support to device hw timestamp.
Moreover this patch fixes following sparse warning:
drivers/iio/imu/st_lsm6dsx/st_lsm6dsx_buffer.c:250:17: warning: Variable length
array is used.
drivers/iio/imu/st_lsm6dsx/st_lsm6dsx_buffer.c:283:55: error: cannot size
expression